
ingress:
#  @schema
#  required: false
#  @schema
#  Enables the ingress controller for JupyterHub.
  enabled: true
  #  @schema
  #  required: false
  #  @schema
#  Enables the creation of the ingress resource.
  create: true
  #  @schema
  #  required: false
  #  @schema
#  The name of the ingress resource to use if create is false.
  name: ""
  #  @schema
  #  required: false
  #  @schema
#  Any annotations to apply to the ingress resource.
  annotations: {}
  #  @schema
  #  required: false
  #  @schema
#  The domain name that the IP address of the ingress will resolve to.
  host: ""
  #  @schema
  #  required: false
  #  @schema
#  The IP address to use for the ingress resource.
  staticIp: ""

managedCertificate:
  #  @schema
  #  required: false
  #  @schema
#  Enables the use of a managed certificate for the ingress.
  enabled: true
  #  @schema
  #  required: false
  #  @schema
#  Enables the creation of the managed certificate resource. Set to false if you are not using Google Cloud
  create: true
  #  @schema
  #  required: false
  #  @schema
#  The name of the managed certificate resource to use if create is false.
  name: ""
  #  @schema
  #  required: false
  #  @schema
#  Any annotations to apply to the managed certificate resource.
  annotations: {}
  #  @schema
  #  required: false
  #  @schema
#  The list of domains to include in the managed certificate.
  domains: []

jupyterhub:
  cull:
    enabled: true
    timeout: 1800
    every: 300
  prePuller:
    continuous:
      enabled: false
  hub:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
  imagePullSecret:
    create: true
    registry: ghcr.io
    username: ""
    password: ""

  scheduling:
    userScheduler:
      enabled: false
  proxy:
    chp:
      resources:
        requests:
          cpu: 50m
          memory: 52Mi
    service:
      type: NodePort

  singleuser:
    cpu:
      guarantee: 2
    memory:
      guarantee: 2G
#    nodeSelector:
#      cloud.google.com/machine-family: "c2"
    cloudMetadata:
      blockWithIptables: false
    networkPolicy:
      enabled: true
      egress:
        - to:
            - ipBlock:
                cidr: 0.0.0.0/0
          ports:
            - port: 21
              protocol: TCP
            - protocol: TCP
    image:
      name: ghcr.io/ajayacst/gnssrefl
      tag: latest
    # `cmd: null` allows the custom CMD of the Jupyter docker-stacks to be used
    # which performs further customization on startup.
    cmd: null
    lifecycleHooks:
      postStart:
        exec:
          command:
            - "sh"
            - "-c"
            - |
              if [ ! -f /home/jovyan/.notebooks_copied ]; then
                  cp -r /etc/skel/* /home/jovyan/
                  touch /home/jovyan/.notebooks_copied
              fi