name: gnssrefl
channels:
- conda-forge
- defaults
dependencies:
- sphinx<7
- sphinx_rtd_theme
- unzip
- gfortran_linux-64
- pip
- wget
- jupyter
- numpy
- pandas
- seaborn
- pip:
     - myst_parser
     - nbsphinx
     - numpydoc
     - sphinxcontrib-apidoc
     - git+https://github.com/kristinemlarson/gnssrefl.git
