name: gnssrefl
channels:
- conda-forge
- defaults
dependencies:
- unzip
- gfortran_linux-64
- pip
- wget
- jupyter
- numpy
- pandas
- seaborn
- pip:
     - myst_parser
     - nbsphinx
     - gnssrefl
#     - git+https://github.com/kristinemlarson/gnssrefl.git
