name: ci

on:
  push:
    branches:
      - "master"
  pull_request: {}

jobs:
  build:
    name: "CI"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build . -t gnssrefl
      - name: Run smoke tests
        run: |
          docker run -v "$PWD:/src" gnssrefl /src/software_tests
      - name: Install pytest
        run: |
          pip3 install 'pytest~=7.2'
      - name: Run unit tests
        run: |
          pytest pytest-mock
