name: Publish Helm Chart
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Update Helm dependencies
        run: |
          for chart in ./package/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Updating dependencies for $chart"
              helm dependency update "$chart"
            fi
          done

      - name: Publish Helm Chart
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: ./jupyter-hub-gnss