ingress:
  enabled: true
  create: true
  name: ""
  annotations: {}
  host: ""
  staticIp: ""

managedCertificate:
  enabled: true
  create: true
  name: "jupyter-hub-managed-cert"
  annotations: {}
  domains: []

jupyterhub:
  hub:
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
  imagePullSecret:
    create: true
    registry: ghcr.io
    username: ""
    password: ""

  scheduling:
    userScheduler:
      enabled: false
  proxy:
    chp:
      resources:
        requests:
          cpu: 50m
          memory: 52Mi
    service:
      type: NodePort

  singleuser:
    cpu:
      guarantee: 1
    nodeSelector:
      cloud.google.com/compute-class: "Balanced"
    cloudMetadata:
      blockWithIptables: false
    networkPolicy:
      enabled: true
      egress:
        - to:
            - ipBlock:
                cidr: 0.0.0.0/0
          ports:
            - port: 21
              protocol: TCP
            - protocol: TCP
    image:
      name: ghcr.io/ajayacst/gnssrefl
      tag: latest
    # `cmd: null` allows the custom CMD of the Jupyter docker-stacks to be used
    # which performs further customization on startup.
    cmd: null
    lifecycleHooks:
      postStart:
        exec:
          command:
            - "sh"
            - "-c"
            - |
              if [ ! -f /home/jovyan/.notebooks_copied ]; then
                  cp -r /etc/skel/* /home/jovyan/
                  touch /home/jovyan/.notebooks_copied
              fi